source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
inhibit_all_warnings!
#plugin 'cocoapods-pod-sign'
#skip_pod_bundle_sign # 用来跳过Xcode对bundle资源的签名

def all_pods
  
#  use_modular_headers!
  use_frameworks!
  #Agora RTC SDK
  pod 'AgoraRtcEngine_Special_iOS', '4.1.1.23'
  #Agora 歌词组件
  pod "ScoreEffectUI", '1.0.2'
  pod 'AgoraLyricsScore', '1.1.2'
  
  # 布局
  pod 'Masonry', '1.1.0'
  # tips
  pod 'SVProgressHUD', '2.2.5'

  #ThirdParty
  pod 'LSTPopView', '0.3.10'
  pod 'Zip'
  pod 'MJRefresh'
  pod 'ZSwiftBaseLib', '0.1.6.2'
  #滚动视图
  pod 'JXCategoryView', '1.6.1'
  # Model
  pod 'YYModel', '1.0.4'
  pod 'YYCategories', '1.0.4'
  # 加载图片
  pod 'SDWebImage', '4.4.8'
  pod 'SDWebImageAPNGCoder'
  
  

  # public
  pod 'AgoraSyncManager', '~> 2.1.6'
  pod 'Bugly','2.5.93'
  pod 'HXPhotoPicker/Lite', '4.1.3'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'KakaJSON'
  pod 'AFNetworking', '4.0.1'
end

target 'AgoraEntScenarios' do
  all_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # 为每个配置添加 `-fstack-protector`
#      config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
#      config.build_settings['OTHER_CFLAGS'] << '-fstack-protector'
      shell_script_path = "Pods/Target Support Files/#{target.name}/#{target.name}-frameworks.sh"
      if File::exist?(shell_script_path)
        shell_script_input_lines = File.readlines(shell_script_path)
        shell_script_output_lines = shell_script_input_lines.map { |line| line.sub("source=\"$(readlink \"${source}\")\"", "source=\"$(readlink -f \"${source}\")\"") }
        File.open(shell_script_path, 'w') do |f|
          shell_script_output_lines.each do |line|
            f.write line
          end
        end
      end
    end
  end
end

system("./libs/setup_podspec.sh")
