source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '10.0'
inhibit_all_warnings!

def all_pods
  
#  use_modular_headers!
  use_frameworks!
  # 网络层
  pod 'AFNetworking', '4.0.1'
  # 布局
  pod 'Masonry', '1.1.0'
  # tips
#  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SVProgressHUD', '2.2.5'
  # 加载图片
  pod 'SDWebImage', '5.0.6'
  # Model
  pod 'YYModel', '1.0.4'
#  pod 'YYCache', '1.0.4'
  pod 'YYCategories', '1.0.4'
  # 键盘
  pod 'IQKeyboardManager', '6.5.10'
  #弹框
  pod 'LEEAlert', '1.6.4'
  #滚动视图
  pod 'JXCategoryView', '1.6.1'
  
  pod 'AgoraSyncManager', '1.1.3'
#  pod 'AgoraSyncManager', :path=> './AgoraEntScenarios/Common/Manager/AgoraSyncManager'
  
  pod 'AgoraRtcEngine_Special_iOS', '4.0.0.130.1'
#  pod 'AgoraRtcEngine_iOS', :path => './libs'

  #ThirdParty
  pod 'HWWeakTimer', '1.0'
  pod 'LSTPopView', '0.3.10'
  pod 'SocketRocket', '0.6.0'
  pod 'Agora-Scene-Utils', '1.0.9'
  
  #歌词组件
  pod 'AgoraLyricsScore', '1.0.8.8'
#  pod 'AgoraLyricsScore', :git => 'https://github.com/AgoraIO-Community/LrcView-iOS.git', :commit => 'f0613f7a8e11aa4e333f1dba2cfb2516d1140367'
  pod 'AgoraRtm_iOS', '1.5.1'
  
  
  # Swift Code Formatter
#  pod 'SwiftFormat/CLI'

  #VoiceChatRoom rely
  pod 'ZSwiftBaseLib', '0.1.6.1'
  pod 'SnapKit', '5.6.0'
  pod 'SVGAPlayer', '2.5.7'
  pod 'KakaJSON', '1.1.2'
  pod 'Agora_Chat_iOS','1.0.8'
  
  pod 'SwiftyBeaver', '1.9.5'
  
  #bugly
  pod 'Bugly','2.5.93'
end

target 'AgoraEntScenarios' do
  all_pods
end



