// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SttMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SttTranslation;
@class SttWord;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SttMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface SttMessageRoot : GPBRootObject
@end

#pragma mark - SttText

typedef GPB_ENUM(SttText_FieldNumber) {
  SttText_FieldNumber_Vendor = 1,
  SttText_FieldNumber_Version = 2,
  SttText_FieldNumber_Seqnum = 3,
  SttText_FieldNumber_Uid = 4,
  SttText_FieldNumber_Flag = 5,
  SttText_FieldNumber_Time = 6,
  SttText_FieldNumber_Lang = 7,
  SttText_FieldNumber_Starttime = 8,
  SttText_FieldNumber_Offtime = 9,
  SttText_FieldNumber_WordsArray = 10,
  SttText_FieldNumber_EndOfSegment = 11,
  SttText_FieldNumber_DurationMs = 12,
  SttText_FieldNumber_DataType = 13,
  SttText_FieldNumber_TransArray = 14,
  SttText_FieldNumber_Culture = 15,
  SttText_FieldNumber_TextTs = 16,
};

GPB_FINAL @interface SttText : GPBMessage

@property(nonatomic, readwrite) int32_t vendor;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t seqnum;

@property(nonatomic, readwrite) int64_t uid;

@property(nonatomic, readwrite) int32_t flag;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) int32_t lang;

@property(nonatomic, readwrite) int32_t starttime;

@property(nonatomic, readwrite) int32_t offtime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SttWord*> *wordsArray;
/** The number of items in @c wordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger wordsArray_Count;

@property(nonatomic, readwrite) BOOL endOfSegment;

@property(nonatomic, readwrite) int32_t durationMs;

/** transcribe ,translate */
@property(nonatomic, readwrite, copy, null_resettable) NSString *dataType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SttTranslation*> *transArray;
/** The number of items in @c transArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *culture;

@property(nonatomic, readwrite) int64_t textTs;

@end

#pragma mark - SttWord

typedef GPB_ENUM(SttWord_FieldNumber) {
  SttWord_FieldNumber_Text = 1,
  SttWord_FieldNumber_StartMs = 2,
  SttWord_FieldNumber_DurationMs = 3,
  SttWord_FieldNumber_IsFinal = 4,
  SttWord_FieldNumber_Confidence = 5,
};

GPB_FINAL @interface SttWord : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite) int32_t startMs;

@property(nonatomic, readwrite) int32_t durationMs;

@property(nonatomic, readwrite) BOOL isFinal;

@property(nonatomic, readwrite) double confidence;

@end

#pragma mark - SttTranslation

typedef GPB_ENUM(SttTranslation_FieldNumber) {
  SttTranslation_FieldNumber_IsFinal = 1,
  SttTranslation_FieldNumber_Lang = 2,
  SttTranslation_FieldNumber_TextsArray = 3,
};

GPB_FINAL @interface SttTranslation : GPBMessage

@property(nonatomic, readwrite) BOOL isFinal;

/** 翻译语言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lang;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *textsArray;
/** The number of items in @c textsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger textsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
